Atom/feature/fab
Funcy-ICT/Funcy_Portfolio_iOS_for_SwiftUI pull request #30
Opened 2022-10-11 08:05 UTC by mersakakey

個人もしくはグループの作品投稿画面への遷移をするボタンを追加しました．
遷移先のページがなかったので，仮の遷移先を追加しました．

FabButtonView()

引数
buttonSize: ボタンのサイズ．初期値は50
buttonColor: ボタンの色．初期値はColor.fabColor
isGroup: ボタンの遷移先．isGroupがtrueならグループの作品投稿画面に遷移します．

この構造体は上位ViewにNavigationViewを必要とします．

<img width="340" alt="スクリーンショット 2022-10-11 17 04 31" src="https://user-images.githubusercontent.com/75288670/195033638-621f1231-dd21-42cc-82b5-269829b1e867.png">

2022-10-11 13:40 UTC, mrs1669 reviewed
![エンジニアを褒めるネコ:さすがです](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/04_%E3%81%95%E3%81%99%E3%81%8C%E3%81%A7%E3%81%99.png)

2022-10-11 13:40 UTC, mrs1669 commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/FabButtonView.swift
> +            })
ここインデント一つ分下ですね

2022-10-11 13:40 UTC, mrs1669 commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/FabButtonView.swift
> +
不要な改行差分

2022-10-11 13:40 UTC, mrs1669 commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/FabButtonView.swift
> +
不要な改行差分

2022-10-11 13:40 UTC, mrs1669 commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/FabButtonView.swift
> +        }
インデントが一つずれていると思います．

2022-10-11 13:40 UTC, mrs1669 commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/FabButtonView.swift
> +struct FabButtonView: View {
ファイル名も含めてですがこの機能(Button)の内容がわかりやすい命名にした方が良いと思います．

`FAB`が`Floating Action Button`の略なのであれば，ファイル名も`FloatingActionButtonView.swift`のようにすることをおすすめします．

詳細は，[Swiftの命名規則に関するページ](https://www.swift.org/documentation/api-design-guidelines/#naming)を読むと良いと思います．
基本的に短くまとめるよりも，長くても良いので伝わる命名を心がけると良いと思います．

2022-10-24 07:40 UTC, mersakakey commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/FabButtonView.swift
> +            if isGroup {
一通り直しました！
インデントの規則がいまいちよくわからないので，自分が理解した範囲での修正ですが．．．
変数等の命名規則は今後参考にします :)

2022-10-24 07:53 UTC, massu116 commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/FloatingActionButtonView.swift
> +            FloatingActionButtonView()
インデントずれ.....です...

2022-10-24 08:11 UTC, mersakakey commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/FloatingActionButtonView.swift
> +            FloatingActionButtonView()
:(

2022-10-24 08:26 UTC, massu116 approved these changes

2022-10-24 08:28 UTC, massu116 reviewed
![image](https://user-images.githubusercontent.com/49420598/197482207-dcc18f75-74f9-4c56-a5aa-844eeba9b97a.png)

2022-10-24 08:52 UTC, massu116 reviewed
![LGTM](https://image.lgtmoon.dev/185344)

2022-11-03 12:55 UTC, mrs1669 approved these changes
![LGTM](http://media.tumblr.com/b999d6fa94d40545edb2dac70623e070/tumblr_inline_n2ztfg6zr01qaxsyz.gif)

2022-11-03 13:33 UTC, mrs1669 requested changes
コンフリクトみます

2022-11-03 13:43 UTC, mrs1669 approved these changes
LGTM!

2022-11-03 13:43 UTC, merged