[add]ユーザアイコンのフレームを追加
Funcy-ICT/Funcy_Portfolio_iOS_for_SwiftUI pull request #31
Opened 2022-10-11 08:22 UTC by mohrn3

## issue

読み込んだ画像をユーザアイコンとして表示するフレームを追加。

## 内容

iconPatternが0のとき、largeサイズで表示する。

<img width="271" alt="スクリーンショット 2022-10-11 17 07 20" src="https://user-images.githubusercontent.com/95894061/195034403-30de9a1f-8891-4571-bab0-06ed504d32de.png">
<img width="230" alt="スクリーンショット 2022-10-11 17 09 31" src="https://user-images.githubusercontent.com/95894061/195034757-21486cd4-e103-4757-b307-f591d545d9e8.png">

iconPatternが1のとき、smallサイズで表示する。

<img width="275" alt="スクリーンショット 2022-10-11 17 06 04" src="https://user-images.githubusercontent.com/95894061/195033872-a5710f2f-5cd7-4b36-8243-0825a5fb1080.png">
<img width="264" alt="スクリーンショット 2022-10-11 17 10 43" src="https://user-images.githubusercontent.com/95894061/195035163-b86ed395-86b0-45c4-9198-3e3c894661e0.png">

2022-10-20 15:28 UTC, KaitoKudou commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/IconView.swift
> +    enum IconPattern: Int {
enumはViewに持たせずに別ファイルに書き出すのが一般的ですね。
Enumsディレクトリを作り、その中にIconPatternを定義するとか。

書いてる本人はlargeが0でsmallが1だとわかりますが、途中で開発に参画した人はぱっと見で把握しずらいと感じました。
もっと言うと、わざわざ数字が振られているということは意味のある数字なのでは？と勘繰ってしまうことになります。(現状のコードを見てみると、large or smallが分かればいいので意味のある数字にはなっていないですね....   今後、large or smallに振られた数字を使って画像の大きさやViewのサイズを調節する予定なら現状のままでもいいかもしれません。)

僕だったら以下のようにenumを定義します。
```
enum IconPattern {
  case large
  case small
}
```
↑これだけで十分かと....

2022-10-20 15:28 UTC, KaitoKudou commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/IconView.swift
> +        switch iconPattern {
上記の僕のレビューに則るなら以下のコードで済みますね。
```
switch iconPattern {
  case large:
    // 処理
  case small:
    // 処理
}
```
↑rawValueで場合わけするよりも、large or smallで場合わけした方が直感的かなと思いました。

2022-10-20 15:28 UTC, KaitoKudou commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/IconView.swift
> +
不要な改行

2022-10-20 15:28 UTC, KaitoKudou commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/IconView.swift
> +    let image: String
今はローカルに画像を配置しているようなので混乱は防げると思いますが、恐らく将来的にはサーバーから画像URLを引っ張ってきて表示するかと思います。(だよね鳥山君？)
そうなるとimageというプロパティが画像名なのか画像URLなのかチーム内でも解釈が割れると思います。
現状、ローカルしか考えないのであればimageNameとかにしといて`// TODO: 将来的にはURLに置き換える`とか書いておけばいいと思います。

2022-10-20 15:41 UTC, KaitoKudou commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/IconView.swift
> +    let image: String
Swiftは幸運なことに動的型付け言語なので、仮にimageの型が把握できていなくてもコンパイル時にエラーを出してくれるので、まあXcodeを信じれば防げるといえば防げる。

2022-10-25 07:08 UTC, KaitoKudou commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/IconView.swift
> +        switch iconPattern {
@massu116 
全パターンを網羅してるから必要ないはず。
default書いたらワーニングが出るような気がする。。。

2022-10-25 07:15 UTC, KaitoKudou commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/IconView.swift
> +        switch iconPattern {
> switch iconPattern { case large: // 処理 default: // 処理(small) }
> でも可読性的には悪い気もして...
確かに2つしかないからなぁ。
この先middleみたいなケースが増えることがあれば、拡張性を考慮してこのままでもいいと思う、、、

2022-10-25 13:22 UTC, massu116 commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/IconView.swift
>                  .scaledToFit()
defaultとlargeが同じ内容なので、.largeと.smallのみでいいと思います

2022-11-15 08:04 UTC, massu116 approved these changes
![LGTM](https://images.lgtmgen.org/b7ad47ee-e0eb-427d-aa5e-ff2fe44d3a91)

2022-11-21 06:16 UTC, zekuta-x requested changes
プレビュー用のimageファイルも消して欲しいです！

2022-11-21 06:16 UTC, zekuta-x commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/IconView.swift
> +#endif
DEBUG文章（プレビュー）はコメントアウトしてpushしてくれるとプロダクトが軽くなるのでお願いしたいです！

2023-02-13 06:01 UTC, zekuta-x approved these changes
LGTMです！

2023-02-13 06:01 UTC, merged