[add] プルリクのテンプレートを追加
Funcy-ICT/Funcy_Portfolio_iOS_for_SwiftUI pull request #35
Opened 2022-11-07 06:12 UTC by massu116

テンプレートを追加しました

2022-11-07 06:51 UTC, zekuta-x requested changes

2022-11-07 06:51 UTC, zekuta-x commented on .github/ISSUE_TEMPLATE/pull_request_template.md
> +
セルフレビューしたとこ書いてほちい！

2022-11-07 06:51 UTC, zekuta-x commented on .github/ISSUE_TEMPLATE/pull_request_template.md
> +
簡単なTodoボックスの形式でOK

2022-11-16 00:18 UTC, zekuta-x approved these changes

2022-11-16 00:22 UTC, zekuta-x approved these changes

2022-11-16 00:22 UTC, zekuta-x commented
直しました

2022-11-21 06:20 UTC, takatakunishi approved these changes
内容確認しました。LGTM

2022-11-21 06:21 UTC, merged