[add] PublishingSettingToggleButtonViewを追加
Funcy-ICT/Funcy_Portfolio_iOS_for_SwiftUI pull request #42
Opened 2022-11-21 06:12 UTC by mersakakey

issue #6

<h2>
self reviewした部分
<h5>

<h2>
self reviewする部分
<h5>
複数環境でのビルド

<h2>説明
<h5>
・PublishingSettingToggleButtonViewの追加
<br>

<h2>やったこと
<h5>
・公開設定の切り替え用トグルボタン追加のためのPublishingSettingToggleButtonViewを追加しました．
<br>

<h2>使い方
<h4>
PublishingSettingToggleButtonView() : View

引数
<h5>
特になし

@stateのbool変数publishingで公開設定を制御します．初期値はfalse
オンの時の背景色：textPinkColor
<br>

<h2>スクリーンショット
<h5>

PublishingSettingToggleButtonView(オン時)
<img src="https://user-images.githubusercontent.com/75288670/201609945-8628ebf4-4ef1-4899-ae82-68b949f6759c.png" width="300">

PublishingSettingToggleButtonView(オフ時)
<img src="https://user-images.githubusercontent.com/75288670/201609965-07369d94-780a-4e6d-bf83-9fd8003acce5.png" width="300">

figma上での該当箇所
<img width="265" alt="177122553-6ff463c0-a592-483c-a6fe-9b4f0b44ec41" src="https://user-images.githubusercontent.com/49420598/200270080-896a42a0-e19d-4958-8fd2-9171290ad1db.png">

<br>

<h2>(あれば)レビュー，チェックしてほしい部分
<h5>

2022-12-02 01:35 UTC, zekuta-x requested changes

2022-12-02 01:35 UTC, zekuta-x commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/PublishingSettingToggleButtonView.swift
> +    }
<img width="977" alt="スクリーンショット 2022-12-02 10 32 23" src="https://user-images.githubusercontent.com/56245434/205194509-4efc3957-30c3-4a2c-972b-598be596d7a5.png">

ここのtoggleだけど引数falseでもbuildすると初期値がonなので修正した方が良いかもしれない

2022-12-02 01:37 UTC, zekuta-x approved these changes
チェックミスしました...
OKです！

2022-12-19 07:08 UTC, massu116 commented
![LGTM](https://image.lgtmoon.dev/105388)

2022-12-19 07:08 UTC, massu116 approved these changes

2022-12-19 16:08 UTC, merged