タグ作成
Funcy-ICT/Funcy_Portfolio_iOS_for_SwiftUI pull request #56
Opened 2023-06-26 07:30 UTC by massu116

issue #29 

<h2>機能説明
<h4>

ex.) hoge機能の実装をしました、huga機能の修正をしました　などを箇条書きで記述
- [ ] 検索タグのatomを追加しました

<h2>懸念事項
<h4>

ex.) iPhoneSEだとUIが崩れる、swiftlintで注意が出る　などの懸念と対策を箇条書きで記述
- [ ]

<h2>使い方 (アトミックデザインにおけるパーツのプルリク以外はこの欄を削除)
<h4>

ex.) templateView(string, string) // 関数名と型を記述
- 現状、リストで表示するタグ名を指定しています。
- ex: item["hoge", "fuga", "piyo"]

<h2>スクリーンショット
<h4>

|開発した部分のスクリーンショット|iPhone14|iPhone8|iPhoneSE(1st)|
|-|-|-|-|
||<img width="333" alt="スクリーンショット 2023-06-26 16 22 59" src="https://github.com/Funcy-ICT/Funcy_Portfolio_iOS_for_SwiftUI/assets/49420598/f7583e55-04da-4bb2-9b47-a893a036c9de">|||

<h2> セルフレビュー
<h4>

ex.)
- [ ] hogeの部分でエラーが出ていたので、fugaを直しました
- [ ] 画面が遷移することを確認しました

<h2>(あれば)レビュー，チェックしてほしい部分
<h4>

ex.)
- [ ] hugaの画面を実機で試して欲しいです
- [ ] ここの書き方あってるか知りたいです

2023-06-29 01:16 UTC, zekuta-x requested changes

2023-06-29 01:16 UTC, zekuta-x commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/TagView.swift
> +//                    .padding(.horizontal, 5)
タグは3つ以上並ぶと改行する設定でお願いします
<img width="191" alt="Screenshot 2023-06-29 at 10 11 57" src="https://github.com/Funcy-ICT/Funcy_Portfolio_iOS_for_SwiftUI/assets/56245434/cfbd6423-af77-4a0f-96f1-0f07c10fe395">

2023-06-29 01:16 UTC, zekuta-x commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/TagView.swift
> +//#if DEBUG
プレビューの方にForEachの処理入れなくて良いんじゃない？

2023-06-29 01:16 UTC, zekuta-x commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/TagView.swift
> +//#if DEBUG
TagViewの方に書いていただけるとありがたいです
（自分のImageSelectView見ればわかるかも）

2023-06-29 01:16 UTC, zekuta-x commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/TagView.swift
> +//        let item = ["hoge", "fuga", "piyo"]
タグの文字数制限をお願いします
（英語６文字以上は... とかで良いかも）

<img width="80" alt="Screenshot 2023-06-29 at 10 12 40" src="https://github.com/Funcy-ICT/Funcy_Portfolio_iOS_for_SwiftUI/assets/56245434/5c8b1fe0-c943-4c73-9513-07ea98850d39">

2023-06-29 01:16 UTC, zekuta-x commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/TagView.swift
> +//        let item = ["hoge", "fuga", "piyo"]
日本語とフォント幅違うので気をつけて確認してみてください

2023-07-02 18:32 UTC, massu116 commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/TagView.swift
> +//#if DEBUG
プレビューの中にForEachを入れていたのは、ビューによってタグの表示が異なるから暫定的にここで表示させていた
(呼び出し先で良しなに改行とかを入れるものだと思っていた)

2023-07-02 18:35 UTC, massu116 commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/TagView.swift
> +//#if DEBUG
![スクリーンショット 2023-07-03 3 34 25](https://github.com/Funcy-ICT/Funcy_Portfolio_iOS_for_SwiftUI/assets/49420598/a3ebff95-0570-434c-8a0f-35a54393ab21)

一覧画面だと横スクロールなので、表示を切り替えできるように指定するしかないかな

2023-07-04 02:07 UTC, zekuta-x commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/TagView.swift
> +//#if DEBUG
なるほ　そういうことか
改行しないバターンと
するパターンつくってもらってもよい？

多分改行はタグ3個で固定して良いと思う

2023-07-15 19:20 UTC, massu116 commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/TagView.swift
> +//        let item = ["hoge", "fuga", "piyo"]
atomのTextViewを使ってるので、そこでフォントを指定するように変更するしかないですね、、、

2023-07-15 20:08 UTC, massu116 commented on portfolio-ios-swiftui/portfolio-ios-swiftui/View/Atom/TagView.swift
> +//        let item = ["hoge", "fuga", "piyo"]
> タグの文字数制限をお願いします （英語６文字以上は... とかで良いかも）
> 
> <img alt="Screenshot 2023-06-29 at 10 12 40" width="80" src="https://user-images.githubusercontent.com/56245434/249647212-5c8b1fe0-c943-4c73-9513-07ea98850d39.png">

現状、frameで文字を削っていますが、モック上でのサイズを考慮すると、日本語で5文字を限度に字数制限をしています。英字だと8文字まで打ててしまいますが、6文字制限とあまり変わらないかなと思っています。
もし、文字数が5文字で足りないとなると、ここもTextViewを変更する必要がありそうです。
![Uploading スクリーンショット 2023-07-16 5.08.08.png…]()

2023-07-20 06:12 UTC, zekuta-x approved these changes
良いと思います！
LGTM

2023-07-20 06:13 UTC, merged